In [1]:
import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Using device: cuda

In [3]:
file_path = "Maindata.xlsx" 
df = pd.read_excel(file_path)

In [4]:
df.head()

   Review_ID                          Review_Text  Rating     Source Sentiment
0          1  Very satisfied with the performance       5   Flipkart  Positive
1          2      Product is okay nothing special       3     Amazon   Neutral
2          3        Terrible experience overall 😤       2  Instagram  Negative
3          4          Terrible experience overall       2      Voice  Negative
4          5                  Not worth the price       2     Amazon  Negative

In [5]:
df.isnull().sum()

Review_ID      0
Review_Text    0
Rating         0
Source         0
Sentiment      0
dtype: int64

In [6]:
df = df[["Review_Text", "Sentiment"]]

In [7]:
df.sample(5)

                                         Review_Text Sentiment
10228   Honestly It works fine but could be better 🙂   Neutral
3097                           Average performance 🙂   Neutral
3617                                 Worth the money  Positive
10474  Okay so Very satisfied with the performance 😍  Positive
11240                          Average performance 🙂   Neutral

In [8]:
label_mapping = {
    "Negative": 0,
    "Neutral": 1,
    "Positive": 2
}

df["label"] = df["Sentiment"].map(label_mapping)

df["label"].value_counts()

label
0    4091
2    3955
1    3954
Name: count, dtype: int64

In [9]:
X = df["Review_Text"]
y = df["label"]

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2, stratify=y, random_state=42
)

In [11]:
X_train = X_train.tolist()
X_test = X_test.tolist()
y_train = y_train.tolist()
y_test = y_test.tolist()

In [12]:
X_train

['Honestly Terrible experience overall 👎',
 'Honestly Absolutely loved the experience',
 'Decent for the price',
 'Very disappointed with the product 😤',
 'Honestly Very satisfied with the performance',
 'So basically Very satisfied with the performance 💯',
 'Terrible experience overall 💔',
 'Absolutely loved the experience 😊',
 'It works fine but could be better',
 'This product is really good and works as expected',
 'This product is really good and works as expected',
 'Quality is very poor',
 'It stopped working after few days',
 'Very satisfied with the performance 😊',
 'Umm Worth the money',
 'Worth the money',
 'Yeah actually Not bad not great',
 'It works fine but could be better',
 'So basically Average performance 😐',
 'So basically Very disappointed with the product 😭',
 'Honestly Not bad not great',
 'Highly recommended for everyone 🔥',
 'Product is okay nothing special 🤔',
 'Absolutely loved the experience',
 'Terrible experience overall 😭',
 'Product is okay nothing special 😐',
 'Very disappointed with the product',
 'Terrible experience overall',
 'Highly recommended for everyone 🔥',
 'Umm It works fine but could be better',
 'This product is really good and works as expected ✨',
 'Quality is very poor 💔',
 'Honestly Not worth the price',
 'Not bad not great 😐',
 'So basically Decent for the price',
 'Not bad not great',
 'Yeah actually Product is okay nothing special',
 'Product is okay nothing special 😐',
 'Not bad not great',
 'So basically Very satisfied with the performance',
 'Okay so Very disappointed with the product',
 'Not worth the price',
 'It works fine but could be better',
 'This product is really good and works as expected 😍',
 'Very satisfied with the performance',
 'So basically Average performance 😐',
 'It works fine but could be better',
 'Absolutely loved the experience 🔥',
 'This product is really good and works as expected 💯',
 'Absolutely loved the experience 😊',
 'Not worth the price 😭',
 'Product is okay nothing special 🙂',
 'Not worth the price 💔',
 'Average performance 🙂',
 'Terrible experience overall 😤',
 'It stopped working after few days 💔',
 'Average performance',
 'Very satisfied with the performance',
 'Not worth the price',
 'It stopped working after few days 😭',
 'Quality is very poor 😭',
 'Highly recommended for everyone 💯',
 'So basically Terrible experience overall',
 'Umm Terrible experience overall',
 'Highly recommended for everyone ✨',
 'It stopped working after few days',
 'Not worth the price',
 'Umm Not worth the price',
 'Decent for the price 🤔',
 'This product is really good and works as expected 😍',
 'Absolutely loved the experience',
 'Very satisfied with the performance',
 'Very disappointed with the product',
 'It stopped working after few days 😭',
 'Umm Average performance 🤔',
 'Average performance',
 'I mean Absolutely loved the experience 💯',
 'Worth the money 💯',
 'Decent for the price',
 'Absolutely loved the experience 😍',
 'Terrible experience overall',
 'This product is really good and works as expected',
 'Umm This product is really good and works as expected',
 'It works fine but could be better 🙂',
 'Very disappointed with the product 💔',
 'Highly recommended for everyone',
 'Decent for the price 🤔',
 'Very disappointed with the product 👎',
 'Not bad not great 🤔',
 'Not worth the price 😤',
 'Terrible experience overall 😡',
 'Highly recommended for everyone 💯',
 'Not bad not great',
 'Terrible experience overall 💔',
 'Umm It stopped working after few days',
 'Very satisfied with the performance',
 'Not worth the price 😤',
 'Not bad not great',
 'Average performance',
 'Not bad not great',
 'Decent for the price',
 'Okay so Highly recommended for everyone',
 'This product is really good and works as expected 👍',
 'Decent for the price 😐',
 'Not bad not great',
 'Very disappointed with the product 😞',
 'Not worth the price 😤',
 'Not bad not great 🤔',
 'So basically Average performance',
 'So basically Average performance',
 'Quality is very poor 💔',
 'Yeah actually Worth the money',
 'This product is really good and works as expected',
 'It works fine but could be better',
 'Okay so Highly recommended for everyone 👍',
 'Very satisfied with the performance',
 'Absolutely loved the experience 😊',
 'This product is really good and works as expected ✨',
 'Decent for the price 😐',
 'Umm Decent for the price',
 'Product is okay nothing special',
 'Product is okay nothing special',
 'Okay so Very satisfied with the performance',
 'Worth the money 👍',
 'Highly recommended for everyone',
 'So basically Very disappointed with the product 💔',
 'Umm It works fine but could be better',
 'Product is okay nothing special',
 'I mean Product is okay nothing special',
 'Honestly Very satisfied with the performance 😍',
 'Very disappointed with the product',
 'Decent for the price',
 'Highly recommended for everyone',
 'It stopped working after few days 😭',
 'It works fine but could be better 🤔',
 'Not bad not great',
 'I mean Terrible experience overall 😞',
 'Not bad not great',
 'So basically Product is okay nothing special',
 'It stopped working after few days',
 'This product is really good and works as expected 😍',
 'Product is okay nothing special 🤔',
 'Highly recommended for everyone 😊',
 'Quality is very poor',
 'Okay so Worth the money',
 'Terrible experience overall',
 'This product is really good and works as expected',
 'It works fine but could be better 🤔',
 'Honestly Decent for the price',
 'It stopped working after few days',
 'I mean Highly recommended for everyone 😊',
 'Very disappointed with the product',
 'Average performance',
 'Average performance 🤔',
 'This product is really good and works as expected',
 'Yeah actually Terrible experience overall 😭',
 'Umm Not worth the price 😞',
 'Absolutely loved the experience 😍',
 'Okay so Not worth the price',
 'This product is really good and works as expected',
 'Honestly Decent for the price',
 'Very satisfied with the performance',
 'Decent for the price',
 'It stopped working after few days 😞',
 'Umm Terrible experience overall 😡',
 'Terrible experience overall',
 'Decent for the price 🤔',
 'Okay so Highly recommended for everyone',
 'This product is really good and works as expected',
 'Worth the money',
 'It stopped working after few days',
 'Decent for the price',
 'Yeah actually Very disappointed with the product',
 'Decent for the price',
 'Yeah actually Not bad not great 😐',
 'Yeah actually Not worth the price 😞',
 'I mean Decent for the price',
 'Quality is very poor',
 'Very disappointed with the product 😤',
 'Highly recommended for everyone',
 'It stopped working after few days 💔',
 'Worth the money 🔥',
 'Quality is very poor 😡',
 'It works fine but could be better',
 'Quality is very poor',
 'I mean Product is okay nothing special 🤔',
 'Not worth the price',
 'Absolutely loved the experience',
 'Not worth the price',
 'Product is okay nothing special 🙂',
 'Absolutely loved the experience 👍',
 'Umm Average performance 😐',
 'Honestly Worth the money 💯',
 'This product is really good and works as expected',
 'This product is really good and works as expected',
 'Decent for the price',
 'It stopped working after few days 😞',
 'Decent for the price',
 'It works fine but could be better',
 'I mean Not worth the price',
 'Quality is very poor 😭',
 'Yeah actually Absolutely loved the experience',
 'Yeah actually Decent for the price 😐',
 'I mean This product is really good and works as expected',
 'Honestly This product is really good and works as expected 😍',
 'Absolutely loved the experience',
 'Very disappointed with the product',
 'Honestly Product is okay nothing special 😐',
 'Terrible experience overall',
 'Very satisfied with the performance',
 'This product is really good and works as expected 😍',
 'Yeah actually Decent for the price',
 'Not worth the price',
 'Not bad not great',
 'It works fine but could be better',
 'Average performance',
 'Worth the money',
 'Highly recommended for everyone',
 'It works fine but could be better',
 'Terrible experience overall',
 'Decent for the price 🤔',
 'Honestly Very satisfied with the performance',
 'Okay so Terrible experience overall 💔',
 'Average performance',
 'It works fine but could be better 🤔',
 'Terrible experience overall 😞',
 'Not worth the price',
 'I mean Not worth the price 👎',
 'Decent for the price',
 'Not worth the price 😤',
 'Umm Very disappointed with the product 💔',
 'Very disappointed with the product',
 'I mean Quality is very poor',
 'Honestly Decent for the price 😐',
 'Worth the money 👍',
 'Yeah actually Absolutely loved the experience 💯',
 'I mean Product is okay nothing special',
 'Absolutely loved the experience 🔥',
 'Highly recommended for everyone 💯',
 'Absolutely loved the experience',
 'Very disappointed with the product 👎',
 'Yeah actually Not bad not great',
 'Not bad not great',
 'Very satisfied with the performance 💯',
 'Product is okay nothing special 🤔',
 'Worth the money',
 'Quality is very poor 💔',
 'Decent for the price 😐',
 'Okay so This product is really good and works as expected 😍',
 'Very satisfied with the performance 💯',
 'Yeah actually Average performance',
 'Not worth the price',
 'Very satisfied with the performance',
 'Okay so Very satisfied with the performance',
 'Decent for the price',
 'Quality is very poor',
 'Absolutely loved the experience 😍',
 'It works fine but could be better',
 'Worth the money',
 'It stopped working after few days 💔',
 'Yeah actually Not bad not great 🤔',
 'Very satisfied with the performance 💯',
 'Honestly Very satisfied with the performance',
 'Quality is very poor',
 'Quality is very poor',
 'It stopped working after few days',
 'Product is okay nothing special 🤔',
 'Okay so This product is really good and works as expected 👍',
 'Product is okay nothing special 🙂',
 'Worth the money',
 'Okay so Worth the money 🔥',
 'I mean Worth the money 👍',
 'This product is really good and works as expected',
 'Not worth the price',
 'It works fine but could be better 🙂',
 'Decent for the price',
 'It works fine but could be better',
 'Umm It works fine but could be better 🙂',
 'So basically Average performance 🙂',
 'So basically Not worth the price',
 'Okay so Very disappointed with the product 😞',
 'Not bad not great',
 'Yeah actually Terrible experience overall',
 'Quality is very poor 😤',
 'Okay so Terrible experience overall',
 'Highly recommended for everyone',
 'Absolutely loved the experience',
 'Very disappointed with the product',
 'This product is really good and works as expected',
 'Yeah actually This product is really good and works as expected',
 'Yeah actually This product is really good and works as expected 😊',
 'Worth the money',
 'Worth the money',
 'It works fine but could be better',
 'Decent for the price',
 'Umm Very satisfied with the performance',
 'It works fine but could be better',
 'Very disappointed with the product 😤',
 'Worth the money 👍',
 'Terrible experience overall 😞',
 'Product is okay nothing special',
 'It works fine but could be better 😐',
 'Decent for the price',
 'Yeah actually Absolutely loved the experience',
 'Very satisfied with the performance 😊',
 'Okay so Decent for the price',
 'Okay so Absolutely loved the experience',
 'Decent for the price',
 'Terrible experience overall',
 'Very disappointed with the product',
 'Umm This product is really good and works as expected 😊',
 'Terrible experience overall',
 'Worth the money',
 'Very satisfied with the performance',
 'Not bad not great',
 'Quality is very poor 😤',
 'Okay so Very satisfied with the performance',
 'I mean Terrible experience overall 😞',
 'Okay so Absolutely loved the experience',
 'Highly recommended for everyone 👍',
 'I mean This product is really good and works as expected 👍',
 'Worth the money',
 'It stopped working after few days 😡',
 'Highly recommended for everyone',
 'Not bad not great',
 'Terrible experience overall',
 'It stopped working after few days 💔',
 'Yeah actually Highly recommended for everyone 😍',
 'Very satisfied with the performance 🔥',
 'Very satisfied with the performance 😍',
 'So basically Decent for the price',
 'Okay so Absolutely loved the experience 👍',
 'Terrible experience overall',
 'I mean Decent for the price',
 'Absolutely loved the experience 💯',
 'Honestly Product is okay nothing special 🤔',
 'Umm Not worth the price 😞',
 'Worth the money',
 'So basically Very satisfied with the performance',
 'Product is okay nothing special',
 'Honestly Average performance 😐',
 'Average performance',
 'Umm Highly recommended for everyone',
 'It stopped working after few days',
 'I mean It stopped working after few days',
 'Quality is very poor 👎',
 'Absolutely loved the experience',
 'It works fine but could be better 🙂',
 'Very disappointed with the product 😞',
 'Not worth the price 😞',
 'Not worth the price 😤',
 'Worth the money 💯',
 'Terrible experience overall',
 'Quality is very poor 😤',
 'Terrible experience overall',
 'Quality is very poor 😭',
 'Very disappointed with the product 👎',
 'Highly recommended for everyone',
 'It works fine but could be better',
 'Umm It works fine but could be better 😐',
 'Very satisfied with the performance 😊',
 'It stopped working after few days 😤',
 'Absolutely loved the experience 😊',
 'Okay so This product is really good and works as expected',
 'Yeah actually It works fine but could be better',
 'Product is okay nothing special',
 'Absolutely loved the experience 🔥',
 'Not worth the price 👎',
 'Honestly Very satisfied with the performance',
 'Very satisfied with the performance',
 'Terrible experience overall 💔',
 'Umm Very satisfied with the performance',
 'Very satisfied with the performance 💯',
 'Highly recommended for everyone',
 'Not bad not great',
 'Terrible experience overall 😭',
 'It works fine but could be better 😐',
 'Honestly Terrible experience overall 👎',
 'Umm Quality is very poor 😞',
 'I mean Quality is very poor 👎',
 'Umm It stopped working after few days',
 'Quality is very poor 😡',
 'Decent for the price 😐',
 'Average performance 🙂',
 'Honestly Decent for the price',
 'So basically It stopped working after few days',
 'This product is really good and works as expected',
 'Not worth the price 👎',
 'So basically Terrible experience overall',
 'Average performance 😐',
 'Decent for the price 🤔',
 'Worth the money 😍',
 'I mean Highly recommended for everyone ✨',
 'Not bad not great',
 'It stopped working after few days',
 'Umm It works fine but could be better 🤔',
 'Not bad not great',
 'Not bad not great 🙂',
 'Umm Highly recommended for everyone 🔥',
 'Product is okay nothing special',
 'So basically Terrible experience overall 😞',
 'Yeah actually It works fine but could be better',
 'Highly recommended for everyone 😍',
 'Absolutely loved the experience',
 'Not worth the price',
 'Quality is very poor',
 'Quality is very poor 😡',
 'Very satisfied with the performance',
 'Not bad not great',
 'Very satisfied with the performance ✨',
 'Okay so Not worth the price 😞',
 'Highly recommended for everyone 🔥',
 'Not bad not great',
 'Okay so Not bad not great 🙂',
 'Highly recommended for everyone',
 'Umm Highly recommended for everyone',
 'Product is okay nothing special',
 'Highly recommended for everyone 😍',
 'This product is really good and works as expected',
 'Honestly Quality is very poor',
 'Quality is very poor 💔',
 'Product is okay nothing special',
 'This product is really good and works as expected ✨',
 'Average performance',
 'So basically Not bad not great',
 'Quality is very poor',
 'Terrible experience overall 😞',
 'Average performance',
 'Very satisfied with the performance',
 'This product is really good and works as expected',
 'Okay so Absolutely loved the experience 🔥',
 'It works fine but could be better 🤔',
 'Very satisfied with the performance 😊',
 'This product is really good and works as expected',
 'Worth the money 🔥',
 'Quality is very poor 💔',
 'I mean Terrible experience overall',
 'Umm Terrible experience overall',
 'Not bad not great',
 'Decent for the price',
 'It stopped working after few days 😤',
 'Not worth the price 😞',
 'I mean Very disappointed with the product 😤',
 'Umm Very satisfied with the performance 😊',
 'Highly recommended for everyone 😍',
 'Honestly Quality is very poor 💔',
 'Product is okay nothing special 🙂',
 'Product is okay nothing special 🙂',
 'So basically Decent for the price 🤔',
 'Terrible experience overall 😡',
 'Not worth the price 😭',
 'Decent for the price 😐',
 'Yeah actually Decent for the price',
 'So basically Average performance',
 'It works fine but could be better 🤔',
 'This product is really good and works as expected 🔥',
 'Terrible experience overall',
 'This product is really good and works as expected 💯',
 'Not bad not great 🙂',
 'Terrible experience overall',
 'Not bad not great 🙂',
 'Quality is very poor',
 'Worth the money 😍',
 'Yeah actually Absolutely loved the experience',
 'Terrible experience overall 😭',
 'So basically Product is okay nothing special',
 'Terrible experience overall',
 'Decent for the price',
 'Umm It works fine but could be better',
 'Worth the money 👍',
 'Okay so Very satisfied with the performance',
 'Decent for the price',
 'It works fine but could be better',
 'Okay so Not worth the price',
 'Quality is very poor',
 'So basically Decent for the price',
 'This product is really good and works as expected',
 'Decent for the price 🤔',
 'Yeah actually Absolutely loved the experience 😍',
 'Absolutely loved the experience 💯',
 'This product is really good and works as expected 👍',
 'It stopped working after few days 😞',
 'Decent for the price',
 'Quality is very poor',
 'I mean It stopped working after few days',
 'So basically Not worth the price',
 'I mean Terrible experience overall 😡',
 'Not bad not great',
 'Average performance',
 'So basically Decent for the price 🙂',
 'Not worth the price',
 'Honestly Very satisfied with the performance',
 'Not worth the price',
 'It works fine but could be better',
 'Decent for the price',
 'Average performance 🤔',
 'This product is really good and works as expected 💯',
 'So basically Highly recommended for everyone 💯',
 'Average performance 🤔',
 'Terrible experience overall',
 'Yeah actually Not worth the price 😤',
 'Worth the money 👍',
 'Not worth the price',
 'Okay so It works fine but could be better',
 'Very satisfied with the performance 👍',
 'Yeah actually Very disappointed with the product',
 'Decent for the price 😐',
 'It works fine but could be better',
 'I mean Average performance 🤔',
 'This product is really good and works as expected',
 'Very disappointed with the product 😞',
 'It stopped working after few days',
 'Average performance',
 'This product is really good and works as expected',
 'Average performance 🙂',
 'Honestly Quality is very poor',
 'Yeah actually It works fine but could be better',
 'I mean This product is really good and works as expected 😊',
 'Very satisfied with the performance',
 'Product is okay nothing special',
 'Okay so Not worth the price',
 'Umm Very satisfied with the performance ✨',
 'Not bad not great',
 'Decent for the price 🤔',
 'It works fine but could be better',
 'It stopped working after few days 😡',
 'Okay so Not worth the price',
 'Absolutely loved the experience',
 'It stopped working after few days',
 'Average performance',
 'Decent for the price 😐',
 'This product is really good and works as expected',
 'This product is really good and works as expected',
 'Terrible experience overall',
 'Yeah actually It works fine but could be better 🙂',
 'Okay so Not worth the price 😭',
 'Decent for the price',
 'Terrible experience overall',
 'Highly recommended for everyone 😊',
 'Umm This product is really good and works as expected 🔥',
 'So basically It stopped working after few days',
 'So basically Worth the money',
 'Absolutely loved the experience',
 'Very disappointed with the product 😞',
 'Very satisfied with the performance',
 'Umm Not bad not great',
 'It stopped working after few days',
 'Not bad not great 🤔',

In [13]:
# Load pretrained BERT tokenizer.
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased") ## Converts texts into proper numbers and token ids to be understood by pretrained BERT

C:\Users\chauh\anaconda3\envs\dl_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [14]:
class SentimentDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            self.texts[idx],
            padding="max_length",
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt"
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels": torch.tensor(self.labels[idx], dtype=torch.long)
        }

In [15]:
train_dataset = SentimentDataset(X_train, y_train, tokenizer)
test_dataset = SentimentDataset(X_test, y_test, tokenizer)

In [16]:
trainloader = DataLoader(train_dataset, batch_size=16, shuffle=True)
testloader = DataLoader(test_dataset, batch_size=16)

In [17]:
batch = next(iter(trainloader))

input_ids = batch["input_ids"].to(device)
attention_mask = batch["attention_mask"].to(device)
labels = batch["labels"].to(device)

print("Input IDs shape:", input_ids.shape)
print("Attention mask shape:", attention_mask.shape)
print("Labels shape:", labels.shape)
print("Device:", input_ids.device)

Input IDs shape: torch.Size([16, 128])
Attention mask shape: torch.Size([16, 128])
Labels shape: torch.Size([16])
Device: cuda:0

In [30]:
##Load Model (Pretrained BERT)

from transformers import AutoModelForSequenceClassification
from torch.optim import AdamW

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=3
)

model.to(device)

# Freeze BERT layers
for param in model.bert.parameters():
    param.requires_grad = False

Loading weights: 100%|████████████████| 199/199 [00:01<00:00, 160.20it/s, Materializing param=bert.pooler.dense.weight]
BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [37]:
optimizer = AdamW(model.parameters(), lr=2e-4) ## Critetia or CrossEntropyLoss is calculated automatically

In [38]:
from tqdm import tqdm

In [39]:
epochs = 14

for epoch in range(epochs):

    model.train()
    total_loss = 0

    for batch in tqdm(trainloader):

        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )

        loss = outputs.loss
        total_loss += loss.item()

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    avg_loss = total_loss / len(trainloader)

    print(f"\nEpoch {epoch+1}/{epochs}")
    print("Training Loss:", avg_loss)

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [00:59<00:00, 10.15it/s]

Epoch 1/14
Training Loss: 0.8956637543439865

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [00:51<00:00, 11.62it/s]

Epoch 2/14
Training Loss: 0.8037018783887228

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [00:56<00:00, 10.57it/s]

Epoch 3/14
Training Loss: 0.7364303902784983

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [00:55<00:00, 10.89it/s]

Epoch 4/14
Training Loss: 0.6803425900638104

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [01:03<00:00,  9.44it/s]

Epoch 5/14
Training Loss: 0.6324368274211883

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [00:50<00:00, 11.77it/s]

Epoch 6/14
Training Loss: 0.5918081237375736

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [00:49<00:00, 12.04it/s]

Epoch 7/14
Training Loss: 0.553322151005268

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [00:49<00:00, 12.09it/s]

Epoch 8/14
Training Loss: 0.5261716488997141

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [00:49<00:00, 12.05it/s]

Epoch 9/14
Training Loss: 0.5045950768887997

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [00:49<00:00, 12.03it/s]

Epoch 10/14
Training Loss: 0.4822255478302638

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [00:49<00:00, 12.05it/s]

Epoch 11/14
Training Loss: 0.4610874746243159

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [00:56<00:00, 10.58it/s]

Epoch 12/14
Training Loss: 0.4388032826781273

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [01:07<00:00,  8.93it/s]

Epoch 13/14
Training Loss: 0.42390022886296114

100%|████████████████████████████████████████████████████████████████████████████████| 600/600 [00:49<00:00, 12.03it/s]

Epoch 14/14
Training Loss: 0.41296167343854906

In [40]:
from sklearn.metrics import accuracy_score

model.eval()

preds = []
labels_all = []

with torch.no_grad():
    for batch in testloader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(input_ids=input_ids,
                        attention_mask=attention_mask)

        logits = outputs.logits
        predictions = torch.argmax(logits, dim=1)

        preds.extend(predictions.cpu().numpy())
        labels_all.extend(labels.cpu().numpy())

accuracy = accuracy_score(labels_all, preds)
print("Validation Accuracy:", accuracy)

Validation Accuracy: 0.9870833333333333

In [42]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(labels_all, preds))
print(confusion_matrix(labels_all, preds))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       818
           1       0.96      1.00      0.98       791
           2       1.00      0.98      0.99       791

    accuracy                           0.99      2400
   macro avg       0.99      0.99      0.99      2400
weighted avg       0.99      0.99      0.99      2400

[[801  17   0]
 [  0 791   0]
 [  2  12 777]]

In [43]:
torch.save(model.state_dict(), "bert_sentiment_model.pth")